--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekEatHeal
build-by-default: true
branches:
- main
projects:
  KygekEatHeal:
    path: ""
    libs:
      - src: thebigcrafter/Hydrogen/Hydrogen
        version: ^1.0.0
...
