--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekEatHeal
build-by-default: true
branches:
- main
projects:
  KygekEatHeal:
    path: ""
    libs:
      - src: thebigcrafter/ktpmpl-cfs/ktpmpl-cfs
        version: ^4.0.0
...
