---
# Eat and heal a player instantly!
# Copyright (C) 2020-2023 KygekTeam
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

name: KygekEatHeal
version: 2.1.1
authors: [KygekTeam, thebigcrafter]
api: 5.0.0
main: KygekTeam\KygekEatHeal\EatHeal
description: Eat and heal a player instantly!
website: https://github.com/thebigcrafter/KygekEatHeal
softdepend: BedrockEconomy

permissions:
  kygekeatheal:
    description: Permission to use all KygekEatHeal commands
    default: true
  kygekeatheal.eat:
    description: Permission to use /eat command
    default: true
  kygekeatheal.heal:
    description: Permission to use /heal command
    default: true
...
